// TEMPORARY DATA

export let role = "admin"; // "admin" | "teacher" | "student" | "parent"

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Ramesh Sharma",
    email: "rameshsharma@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "Thamel, Kathmandu, Nepal",
  },
  {3
    id: 2,
    teacherId: "1234567890",
    name: "Sita Thapa",
    email: "sitathapa@gmail.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "Boudha, Kathmandu, Nepal",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Bikash Gurung",
    email: "bikashgurung@gmail.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Lakeside, Pokhara, Nepal",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Rajesh Adhikari",
    email: "rajeshadhikari@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "Durbar Marg, Kathmandu, Nepal",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Gita Rai",
    email: "gitarai@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "Jhamsikhel, Lalitpur, Nepal",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Sunita Shrestha",
    email: "sunitashrestha@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "Patan Dhoka, Lalitpur, Nepal",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Deepak Tamang",
    email: "deepaktamang@gmail.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "Baneshwor, Kathmandu, Nepal",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Kamala Karki",
    email: "kamalakarki@gmail.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "Kalimati, Kathmandu, Nepal",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Anil Poudel",
    email: "anilpoudel@gmail.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "Sanepa, Lalitpur, Nepal",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Krishna Bhattarai",
    email: "krishnabhattarai@gmail.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Bhaktapur Durbar Square, Bhaktapur, Nepal",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Aarav Pradhan",
    email: "aaravpradhan@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "New Baneshwor, Kathmandu, Nepal",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Priya Maharjan",
    email: "priyamaharjan@gmail.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Mangal Bazar, Lalitpur, Nepal",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Bibek Lama",
    email: "bibeklama@gmail.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Boudhanath, Kathmandu, Nepal",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Sujal Basnet",
    email: "sujalbasnet@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Baluwatar, Kathmandu, Nepal",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Anisha Khadka",
    email: "anishakhadka@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Naxal, Kathmandu, Nepal",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Sarita Magar",
    email: "saritamagar@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Chabahil, Kathmandu, Nepal",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Rohan Subedi",
    email: "rohansubedi@gmail.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Koteshwor, Kathmandu, Nepal",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Nisha Rana",
    email: "nisharana@gmail.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Kupondole, Lalitpur, Nepal",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Sujan Thapa",
    email: "sujanthapa@gmail.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Dhapasi, Kathmandu, Nepal",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Kritika Pandey",
    email: "kritikapandey@gmail.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Suryabinayak, Bhaktapur, Nepal",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Gopal Pradhan",
    students: ["Aarav Pradhan"],
    email: "gopalpradhan@gmail.com",
    phone: "1234567890",
    address: "New Baneshwor, Kathmandu, Nepal",
  },
  {
    id: 2,
    name: "Maya Maharjan",
    students: ["Priya Maharjan"],
    email: "mayamaharjan@gmail.com",
    phone: "1234567890",
    address: "Mangal Bazar, Lalitpur, Nepal",
  },
  {
    id: 3,
    name: "Nabin Lama",
    students: ["Bibek Lama"],
    email: "nabinlama@gmail.com",
    phone: "1234567890",
    address: "Boudhanath, Kathmandu, Nepal",
  },
  {
    id: 4,
    name: "Prakash Basnet",
    students: ["Sujal Basnet", "Suman Basnet"],
    email: "prakashbasnet@gmail.com",
    phone: "1234567890",
    address: "Baluwatar, Kathmandu, Nepal",
  },
  {
    id: 5,
    name: "Sarita Khadka",
    students: ["Anisha Khadka"],
    email: "saritakhadka@gmail.com",
    phone: "1234567890",
    address: "Naxal, Kathmandu, Nepal",
  },
  {
    id: 6,
    name: "Mohan Magar",
    students: ["Sarita Magar"],
    email: "mohanmagar@gmail.com",
    phone: "1234567890",
    address: "Chabahil, Kathmandu, Nepal",
  },
  {
    id: 7,
    name: "Ramesh Subedi",
    students: ["Rohan Subedi", "Riya Subedi"],
    email: "rameshsubedi@gmail.com",
    phone: "1234567890",
    address: "Koteshwor, Kathmandu, Nepal",
  },
  {
    id: 8,
    name: "Dipak Rana",
    students: ["Nisha Rana"],
    email: "dipakrana@gmail.com",
    phone: "1234567890",
    address: "Kupondole, Lalitpur, Nepal",
  },
  {
    id: 9,
    name: "Binod Thapa",
    students: ["Sujan Thapa", "Sneha Thapa"],
    email: "binodthapa@gmail.com",
    phone: "1234567890",
    address: "Dhapasi, Kathmandu, Nepal",
  },
  {
    id: 10,
    name: "Rajendra Pandey",
    students: ["Kritika Pandey"],
    email: "rajendrapandey@gmail.com",
    phone: "1234567890",
    address: "Suryabinayak, Bhaktapur, Nepal",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Ramesh Sharma", "Kamala Karki"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Deepak Tamang", "Anil Poudel"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Sita Thapa", "Sunita Shrestha"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Sita Thapa", "Bikash Gurung"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Bikash Gurung", "Krishna Bhattarai"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Rajesh Adhikari", "Gita Rai"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Mohan Khatri", "Sushila Karki"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Prakash Basnet", "Shreya Thapa"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gita Rai", "Sangita Rana"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Anil Poudel", "Binita Sharma"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Ramesh Sharma",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Sita Thapa",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Bikash Gurung",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Rajesh Adhikari",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Gita Rai",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Sunita Shrestha",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Deepak Tamang",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Kamala Karki",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Anil Poudel",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Krishna Bhattarai",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ramesh Sharma",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Deepak Tamang",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Bikash Gurung",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Rajesh Adhikari",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Prakash Basnet",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Gita Rai",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Rajesh Adhikari",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mohan Khatri",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Sita Thapa",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Sita Thapa",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ramesh Sharma",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Deepak Tamang",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Bikash Gurung",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Rajesh Adhikari",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Prakash Basnet",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Gita Rai",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Rajesh Adhikari",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mohan Khatri",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Sita Thapa",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Sunita Shrestha",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ramesh Sharma",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Deepak Tamang",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Bikash Gurung",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Rajesh Adhikari",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Prakash Basnet",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Gita Rai",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Rajesh Adhikari",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mohan Khatri",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Sita Thapa",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Sunita Shrestha",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Ramesh Sharma",
    student: "Aarav Pradhan",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Deepak Tamang",
    student: "Priya Maharjan",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Bikash Gurung",
    student: "Bibek Lama",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Rajesh Adhikari",
    student: "Sujal Basnet",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Prakash Basnet",
    student: "Anisha Khadka",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Gita Rai",
    student: "Sarita Magar",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Rajesh Adhikari",
    student: "Rohan Subedi",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Mohan Khatri",
    student: "Nisha Rana",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Sita Thapa",
    student: "Sujan Thapa",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Sunita Shrestha",
    student: "Kritika Pandey",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 6, 7, 8, 0),
    end: new Date(2026, 6, 7, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 6, 7, 9, 0),
    end: new Date(2026, 6, 7, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 6, 7, 10, 0),
    end: new Date(2026, 6, 7, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 6, 7, 11, 0),
    end: new Date(2026, 6, 7, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 6, 7, 13, 0),
    end: new Date(2026, 6, 7, 13, 45),
  },
  {
    title: "Nepali",
    allDay: false,
    start: new Date(2026, 6, 7, 14, 0),
    end: new Date(2026, 6, 7, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 6, 8, 9, 0),
    end: new Date(2026, 6, 8, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 6, 8, 10, 0),
    end: new Date(2026, 6, 8, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 6, 8, 11, 0),
    end: new Date(2026, 6, 8, 11, 45),
  },

  {
    title: "Nepali",
    allDay: false,
    start: new Date(2026, 6, 8, 14, 0),
    end: new Date(2026, 6, 8, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 6, 9, 8, 0),
    end: new Date(2026, 6, 9, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 6, 9, 10, 0),
    end: new Date(2026, 6, 9, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 6, 9, 13, 0),
    end: new Date(2026, 6, 9, 13, 45),
  },
  {
    title: "Nepali",
    allDay: false,
    start: new Date(2026, 6, 9, 14, 0),
    end: new Date(2026, 6, 9, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 6, 10, 9, 0),
    end: new Date(2026, 6, 10, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 6, 10, 10, 0),
    end: new Date(2026, 6, 10, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 6, 10, 11, 0),
    end: new Date(2026, 6, 10, 11, 45),
  },

  {
    title: "Nepali",
    allDay: false,
    start: new Date(2026, 6, 10, 14, 0),
    end: new Date(2026, 6, 10, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 6, 11, 8, 0),
    end: new Date(2026, 6, 11, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 6, 11, 9, 0),
    end: new Date(2026, 6, 11, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 6, 11, 11, 0),
    end: new Date(2026, 6, 11, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 6, 11, 13, 0),
    end: new Date(2026, 6, 11, 13, 45),
  },
  {
    title: "Nepali",
    allDay: false,
    start: new Date(2026, 6, 11, 14, 0),
    end: new Date(2026, 6, 11, 14, 45),
  },

  {
    title: "computer",
    allDay: false,
    start: new Date(2026, 6, 7, 15, 0),
    end: new Date(2026, 6, 7, 15, 45),
  }
];